#!/usr/bin/env node
import { program } from "commander";
import * as fs from "fs";
import * as path from "path";
import { buildFromSource, serialize } from "@brick/core";

// Peggy grammar require — brick-core must be built first
function requireParser() {
  const coreRoot = path.dirname(require.resolve("@brick/core"));
  // grammar.js lives in the src dir relative to the built dist
  const grammarPath = path.join(coreRoot, "..", "src", "grammar.js");
  return require(grammarPath);
}

function loadAndParse(file: string) {
  const absPath = path.resolve(file);
  if (!fs.existsSync(absPath)) {
    console.error(`❌  File not found: ${absPath}`);
    process.exit(1);
  }
  if (!absPath.endsWith(".brick")) {
    console.error(`❌  Expected a .brick file, got: ${absPath}`);
    process.exit(1);
  }
  const source = fs.readFileSync(absPath, "utf8");
  return { source, absPath };
}

// ── brick build ───────────────────────────────────────────────────────────────

program
  .command("build <file>")
  .description("Compile a .brick file to runbook JSON")
  .option("-o, --out <path>", "Output path for the JSON file")
  .option("--pretty", "Pretty-print the JSON output", true)
  .action((file: string, opts: { out?: string; pretty: boolean }) => {
    const { source, absPath } = loadAndParse(file);
    const { steps, diagnostics } = buildFromSource(source);

    const errors = diagnostics.filter(d => d.severity === "error");
    const warnings = diagnostics.filter(d => d.severity === "warning");

    if (warnings.length > 0) {
      warnings.forEach(w => {
        const loc = w.line ? ` (line ${w.line})` : "";
        console.warn(`⚠️   warning${loc}: ${w.message}`);
      });
    }

    if (errors.length > 0) {
      errors.forEach(e => {
        const loc = e.line ? ` (line ${e.line})` : "";
        console.error(`❌  error${loc}: ${e.message}`);
      });
      process.exit(1);
    }

    const json = opts.pretty
      ? JSON.stringify(steps, null, 2)
      : JSON.stringify(steps);

    const outPath = opts.out ?? absPath.replace(/\.brick$/, ".json");
    fs.writeFileSync(outPath, json, "utf8");
    console.log(`✅  Built ${steps.length} step${steps.length !== 1 ? "s" : ""} → ${path.relative(process.cwd(), outPath)}`);
  });

// ── brick lint ────────────────────────────────────────────────────────────────

program
  .command("lint <file>")
  .description("Lint a .brick file for errors and warnings")
  .option("--json", "Output diagnostics as JSON")
  .action((file: string, opts: { json: boolean }) => {
    const { source } = loadAndParse(file);
    const { diagnostics } = buildFromSource(source);

    if (opts.json) {
      console.log(JSON.stringify(diagnostics, null, 2));
      process.exit(diagnostics.some(d => d.severity === "error") ? 1 : 0);
    }

    if (diagnostics.length === 0) {
      console.log("✅  No issues found");
      return;
    }

    let hasErrors = false;
    for (const d of diagnostics) {
      const icon = d.severity === "error" ? "❌" : d.severity === "warning" ? "⚠️ " : "ℹ️ ";
      const loc = d.line ? `:${d.line}${d.column ? `:${d.column}` : ""}` : "";
      console.log(`${icon}  ${path.basename(file)}${loc}  ${d.message}`);
      if (d.severity === "error") hasErrors = true;
    }

    if (hasErrors) process.exit(1);
  });

// ── brick print ───────────────────────────────────────────────────────────────

program
  .command("print <file>")
  .description("Parse and re-serialize a .brick file (pretty-print / round-trip check)")
  .action((file: string) => {
    const { source } = loadAndParse(file);
    const { steps, diagnostics } = buildFromSource(source);

    const errors = diagnostics.filter(d => d.severity === "error");
    if (errors.length > 0) {
      errors.forEach(e => console.error(`❌  ${e.message}`));
      process.exit(1);
    }

    console.log(serialize(steps));
  });

// ── brick new ────────────────────────────────────────────────────────────────

program
  .command("new [name]")
  .description("Create a new main.brick file from a template")
  .action((name = "main") => {
    const outPath = path.resolve(`${name}.brick`);
    if (fs.existsSync(outPath)) {
      console.error(`❌  File already exists: ${outPath}`);
      process.exit(1);
    }
    const template = `// ${name}.brick
// Generated by brick new

main() {
  // Start writing your automation here
  go to "https://example.com"
  screenshot -> @snap
  ai "Describe what you see on the page" -> @description
}
`;
    fs.writeFileSync(outPath, template, "utf8");
    console.log(`✅  Created ${path.relative(process.cwd(), outPath)}`);
  });

// ── CLI entry ─────────────────────────────────────────────────────────────────

program
  .name("brick")
  .description("The Brick DSL toolchain")
  .version("0.1.0");

program.parse(process.argv);
